INSERT INTO series DEFAULT VALUES;
INSERT INTO series DEFAULT VALUES;

INSERT INTO subgenres DEFAULT VALUES;
INSERT INTO subgenres DEFAULT VALUES;

INSERT INTO authors DEFAULT VALUES;
INSERT INTO authors DEFAULT VALUES;

INSERT INTO books DEFAULT VALUES;
INSERT INTO books DEFAULT VALUES;
INSERT INTO books DEFAULT VALUES;
INSERT INTO books DEFAULT VALUES;
INSERT INTO books DEFAULT VALUES;
INSERT INTO books DEFAULT VALUES;

INSERT INTO characters DEFAULT VALUES;
INSERT INTO characters DEFAULT VALUES;
INSERT INTO characters DEFAULT VALUES;
INSERT INTO characters DEFAULT VALUES;
INSERT INTO characters DEFAULT VALUES;
INSERT INTO characters DEFAULT VALUES;
INSERT INTO characters DEFAULT VALUES;
INSERT INTO characters DEFAULT VALUES;

INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;
INSERT INTO character_books DEFAULT VALUES;